// Generated by npm run sync-abi from deployments/sepolia.json.
import type { Address } from 'viem';

export const SEPOLIA_DEPLOYMENT = {
  chainId: 11155111,
  contractAddress: '0x85DBE339432cd7960FADFef78e2E6981025bD4BA' as Address,
  usdcAddress: '0x1c7D4B196Cb0C7B01d743Fbc6116a902379C7238' as Address,
  deploymentBlock: 11287638n,
  ethUsdFeed: '0x694AA1769357215DE4FAC081bf1f309aDC325306' as Address,
  defaultArbitrator: '0xF176B879e2D37ba20A8ba8e219D0FbB44Ce4e589' as Address,
} as const;
