/**
 * Generates every frontend/subgraph contract artifact from the compiled Hardhat
 * artifact and the canonical Sepolia deployment record.
 *
 * `npm run sync-abi` updates generated files.
 * `npm run check:abi` exits non-zero when generated files or addresses drift.
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const check = process.argv.includes('--check');
const artifactPath = path.join(root, 'artifacts', 'contracts', 'FreelanceEscrow.sol', 'FreelanceEscrow.json');
const deploymentPath = path.join(root, 'deployments', 'sepolia.json');

if (!fs.existsSync(artifactPath)) {
  console.error('No artifact found — run `npx hardhat compile` first.');
  process.exit(1);
}

const { abi } = JSON.parse(fs.readFileSync(artifactPath, 'utf8'));
const deployment = JSON.parse(fs.readFileSync(deploymentPath, 'utf8'));
const normalizedAbi = JSON.stringify(abi, null, 2);
const frontendAbi = `// Generated by npm run sync-abi. Do not edit manually.\nimport type { Abi } from 'viem';\n\nexport const freelanceEscrowAbi = ${normalizedAbi} as const satisfies Abi;\n`;
const frontendDeployment = `// Generated by npm run sync-abi from deployments/sepolia.json.\nimport type { Address } from 'viem';\n\nexport const SEPOLIA_DEPLOYMENT = {\n  chainId: ${deployment.chainId},\n  contractAddress: '${deployment.address}' as Address,\n  usdcAddress: '${deployment.usdcAddress}' as Address,\n  deploymentBlock: ${deployment.blockNumber}n,\n  ethUsdFeed: '${deployment.constructorArgs.ethUsdFeed}' as Address,\n  defaultArbitrator: '${deployment.constructorArgs.arbitrator}' as Address,\n} as const;\n`;

const targets = [
  [path.join(root, 'frontend', 'src', 'abi', 'FreelanceEscrow.ts'), frontendAbi],
  [path.join(root, 'frontend', 'src', 'config', 'deployment.ts'), frontendDeployment],
  [path.join(root, 'subgraph', 'abis', 'FreelanceEscrow.json'), `${normalizedAbi}\n`],
];

let drift = false;
for (const [target, expected] of targets) {
  const relative = path.relative(root, target);
  if (check) {
    const actual = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';
    if (actual !== expected) {
      console.error(`drift: ${relative}`);
      drift = true;
    }
  } else {
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, expected);
    console.log(`synced → ${relative}`);
  }
}

const subgraph = fs.readFileSync(path.join(root, 'subgraph', 'subgraph.yaml'), 'utf8');
const readme = fs.readFileSync(path.join(root, 'README.md'), 'utf8');
const legacyFrontendAbi = path.join(root, 'frontend', 'src', 'config', 'FreelanceEscrow.abi.json');
const expectedAddress = deployment.address.toLowerCase();
const manifestAddress = subgraph.match(/address:\s*"(0x[a-fA-F0-9]{40})"/)?.[1]?.toLowerCase();
const manifestBlock = Number(subgraph.match(/startBlock:\s*(\d+)/)?.[1]);

if (deployment.network !== 'sepolia' || deployment.chainId !== 11155111) {
  console.error('drift: deployments/sepolia.json must identify Sepolia chain 11155111');
  drift = true;
}
if (manifestAddress !== expectedAddress || manifestBlock !== deployment.blockNumber) {
  console.error('drift: subgraph/subgraph.yaml does not match deployments/sepolia.json');
  drift = true;
}
if (!readme.toLowerCase().includes(expectedAddress)) {
  console.error('drift: README.md does not contain the canonical deployed contract address');
  drift = true;
}
if (!readme.toLowerCase().includes(deployment.usdcAddress.toLowerCase())) {
  console.error('drift: README.md does not contain the supported Sepolia USDC address');
  drift = true;
}
if (fs.existsSync(legacyFrontendAbi)) {
  console.error('drift: remove the legacy frontend JSON ABI; use the generated TypeScript ABI');
  drift = true;
}

if (drift) process.exit(1);
console.log(`${check ? 'verified' : 'ABI entries'}: ${abi.length}`);
